server {
    listen 80;
    # Cambia 'tu-dominio.com' por la IP de tu servidor de IONOS o tu dominio real
    server_name 198.71.54.179;

    # Redirección obligatoria a HTTPS (Requisito del profesor)
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 198.71.54.179;

    # Estas rutas deben coincidir con donde Certbot guarde tus llaves en el servidor
    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Importante para React Router
    }
}